# Generated by Django 3.2.25 on 2024-03-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
    ]
