# Generated by Django 3.2.25 on 2024-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0002_remove_destination_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
